Move library What Input JS from CDN to local file
openfed/kiso pull request #105
Opened 2023-09-06 06:58 UTC by jclemmenb4y

Move What Input JS from CDN to local file

2023-09-08 07:28 UTC, smillart commented
@jclemmenb4y Is there any JIRA ticket for this task?

2023-09-08 14:11 UTC, jclemmenb4y commented
> @jclemmenb4y Is there any JIRA ticket for this task?

Yes, it's already assigned to you : https://jira.hosted-tools.com/browse/BOSA_0100-237

2023-09-15 09:22 UTC, smillart requested changes

2023-09-15 09:22 UTC, smillart commented on kiso.libraries.yml
> +    js/contrib/what-input/what-input.min.js: {}
@rutiolma Same question as for PR #104... To avoid bloading the **Kiso (基礎)** theme folder with a whole series of local JS libraries, wouldn't it be more appropriate to install "What Input?" inside the `/libraries` folder using the Openfed `composer.json` file, as we've already done for the "ARIA Accordion" library?

```suggestion
    /libraries/what-input/dist/what-input.min.js: { minified: true }
```

2023-09-18 12:07 UTC, rutiolma commented on kiso.libraries.yml
> +    js/contrib/what-input/what-input.min.js: {}
Indeed, this should be included in libraries. I'll add it to Openfed.

2023-09-21 07:11 UTC, smillart commented on kiso.libraries.yml
> +    js/contrib/what-input/what-input.min.js: {}
Thanks @rutiolma, be aware I made the same request for the "Splide" accessible slider/carousel TypeScript in the PR #104.

2023-10-04 08:31 UTC, smillart approved these changes

2023-10-04 08:37 UTC, merged