#64 empty regions verification optimisation
openfed/kiso pull request #124
Opened 2024-07-11 07:30 UTC by GyD

Hi team,

Here is my attempt to improve the performance of Kiso.

The has_{region} functionality is kept so theme using it still can use it.
Functions used to check if region is empty are kept but adapted so theme using it still can use it.
A per region variable page_{region} is introduced for future themes, that variable store the rendered output of the page.region so it can be called in theme without re-redering the region again.
A function _kiso_render_region is introduced to avoid calling \Drupal::service('renderer')->render($region); each time *but* also not mark the region as rendered since the region is not passed by reference. This way if you need to alter region content after kiso_preprocess_html and kiso_preprocess_page it still behave as drupal core.

2024-07-11 10:11 UTC, rutiolma commented on includes/preprocess.utils.inc
> +  $text = strip_tags($markup, [
It's ignoring the allowed_tags param now but we should still support it

2024-07-11 10:11 UTC, rutiolma commented on kiso.info.yml
> -
I would keep this, so we start using it on new projects.
This module will be added on the next release of Openfed

2024-07-12 07:41 UTC, rutiolma approved these changes
Looks good to me

2024-07-12 10:23 UTC, smillart requested changes
Just a comment added regarding the `kiso_preprocess_html()` function that contains a potentially unused `$variables['page_tools']` variable. @GyD  Could you please take a look? Thanks!

2024-07-12 10:23 UTC, smillart commented on includes/preprocess.html.inc
> +  $variables['page_tools'] = _kiso_render_region($variables['page']['tools']);
@GyD What's the purpose of this `$variables['page_tools']` variable defined here from the `kiso_preprocess_html()` function? I cannot see any `page_tools` variable called inside the `html.html.twig` template...

2024-07-12 13:17 UTC, smillart approved these changes

2024-07-12 13:25 UTC, merged