Fix/#76: Excluded links that are already handled by the script
openfed/kiso pull request #78
Opened 2023-02-23 16:21 UTC by kzenmatthias

The script adds the attribute `data-extlink` to links where icons are being added. We can use this to exclude links with already have an icon.

2023-02-27 08:29 UTC, GyD reviewed
test

2023-02-27 08:29 UTC, GyD commented on js/sources/extlink-window.js
> +      var links =  context.querySelectorAll(
just a test

2023-02-27 08:30 UTC, smillart requested changes

2023-02-27 08:46 UTC, kzenmatthias commented on js/sources/extlink-window.js
> +        'a[href]:not([href^="#"]):not([href^="tel:"]):not([role="tab"]):not([role="button"]):not(data-extlink)'
I've added data-extlink-window and ignored this attribute in the selector.
Changes can be found in the new commit.

2023-02-28 08:41 UTC, smillart reviewed
I need to test the branch on my local. I'll keep you posted...

2023-02-28 14:06 UTC, smillart approved these changes
It seems your modifications no longer produce any JS error in the console! All `<a>` elements with the `data-extlink-window` attribute are safely ignored. I approved the PR... Congrats!

2023-02-28 14:44 UTC, merged